name: AWS DEPLOY TO STAGING

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  workflow_dispatch:

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PW: ${{ secrets.DB_PW }}
      DB_NAME: ${{ secrets.DB_NAME }}
      PORT: ${{ secrets.PORT }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: dev
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = ${{ env.DB_HOST }} >> .env
          echo DB_USER = ${{ env.DB_USER }} >> .env
          echo DB_PW = ${{ env.DB_PW }} >> .env
          echo DB_NAME = ${{ env.DB_NAME }} >> .env
          echo PORT = ${{ env.PORT }} >> .env
        
      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "project2.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/2025/project2/t6"
        
      - name: Execute SSH Commands on Remote Server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@project2.eaglesoftwareteam.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/2025/project2/t6
            npm install
            sudo systemctl stop course-backend-t6
            sudo cp course-backend-t6.service /lib/systemd/system/course-backend-t6.service
            sudo systemctl daemon-reload
            sudo systemctl start course-backend-t6

